[package]
name = "learningrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"

[dependencies]
# tokio async
bevy = {version = "0.6", features = ["dynamic"]}